/*
Copyright 2019 The OpenEBS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package pproperty

import (
	"fmt"
	"os/exec"
	"reflect"
	"runtime"
	"strings"

	"github.com/openebs/maya/pkg/zfs/cmd/v1alpha1/bin"
	"github.com/pkg/errors"
)

//PoolProperty defines structure for pool 'Property' operation
type PoolProperty struct {
	//list of property
	PropList []string

	//set property
	OpSet bool

	//pool name
	Pool string

	//command string
	Command string

	// checks is list of predicate function used for validating object
	checks []PredicateFunc

	// error
	err error
}

// NewPoolProperty returns new instance of object PoolProperty
func NewPoolProperty() *PoolProperty {
	return &PoolProperty{}
}

// WithCheck add given check to checks list
func (p *PoolProperty) WithCheck(check ...PredicateFunc) *PoolProperty {
	p.checks = append(p.checks, check...)
	return p
}

// WithProperty method fills the PropList field of PoolProperty object.
func (p *PoolProperty) WithProperty(key, value string) *PoolProperty {
	p.PropList = append(p.PropList, fmt.Sprintf("%s=%s", key, value))
	return p
}

// WithOpSet method fills the OpSet field of PoolProperty object.
func (p *PoolProperty) WithOpSet(OpSet bool) *PoolProperty {
	p.OpSet = OpSet
	return p
}

// WithPool method fills the Pool field of PoolProperty object.
func (p *PoolProperty) WithPool(Pool string) *PoolProperty {
	p.Pool = Pool
	return p
}

// WithCommand method fills the Command field of PoolProperty object.
func (p *PoolProperty) WithCommand(Command string) *PoolProperty {
	p.Command = Command
	return p
}

// Validate is to validate generated PoolProperty object by builder
func (p *PoolProperty) Validate() *PoolProperty {
	for _, check := range p.checks {
		if !check(p) {
			p.err = errors.Wrapf(p.err, "validation failed {%v}", runtime.FuncForPC(reflect.ValueOf(check).Pointer()).Name())
		}
	}
	return p
}

// Execute is to execute generated PoolProperty object
func (p *PoolProperty) Execute() ([]byte, error) {
	p, err := p.Build()
	if err != nil {
		return nil, err
	}
	// execute command here
	return exec.Command(bin.ZPOOL, p.Command).CombinedOutput()
}

// Build returns the PoolProperty object generated by builder
func (p *PoolProperty) Build() (*PoolProperty, error) {
	var c strings.Builder
	p = p.Validate()

	if IsOpSet()(p) {
		p.appendCommand(c, fmt.Sprintf(" set "))
	} else {
		p.appendCommand(c, fmt.Sprintf(" get "))
	}

	if IsPropListSet()(p) {
		for _, v := range p.PropList {
			p.appendCommand(c, fmt.Sprintf(" -o %s ", v))
		}
	}
	p.appendCommand(c, p.Pool)
	p.Command = c.String()
	return p, p.err
}

// appendCommand append string to given string builder
func (p *PoolProperty) appendCommand(c strings.Builder, cmd string) {
	_, err := c.WriteString(cmd)
	if err != nil {
		p.err = errors.Wrapf(p.err, "Failed to append cmd{%s} : %s", cmd, err.Error())
	}
}
