kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-vol1-1r-claim
  namespace: jiva-test
spec:
  storageClassName: jiva-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
