package command

import (
	"testing"

	"github.com/openebs/maya/pkg/apis/openebs.io/v1alpha1"
	"github.com/openebs/maya/types/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestDisplayStats(t *testing.T) {
	validStats := map[string]struct {
		cmdOptions   *CmdVolumeOptions
		replicaStats map[int]*ReplicaStats
		initialStats v1.VolumeMetrics
		finalStats   v1.VolumeMetrics
		output       error
		replicaCount int
		volume       VolumeInfo
	}{
		"StatsStdWhenReplicaIs0": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: nil,
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       0,
				RevisionCounter:      0,
				SectorSize:           "0",
				Size:                 "0",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13162.971420756,
				UsedBlocks:           "0",
				UsedLogicalBlocks:    "0",
				WriteIOPS:            "0",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       0,
				RevisionCounter:      0,
				SectorSize:           "0",
				Size:                 "0",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "0",
				UsedLogicalBlocks:    "0",
				WriteIOPS:            "0",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},

		"StatsStdWhenReplicaIs1": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       2,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       2,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsStdWhenReplicaIs2": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       2,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       2,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsJSONWhenReplicaIs3": {
			cmdOptions: &CmdVolumeOptions{
				json:    "json",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       2,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       3,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsStdWhenReplicaIs4": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
				3: {
					Replica:         "10.10.10.12",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsStdWhenReplicaIs4AndOneErrorPullBack": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "ErrImagePull",
					DataUpdateIndex: "Unknown",
				},
				3: {
					Replica:         "10.10.10.12",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsStdWhenReplicaIs4AndOneCrashLoopBackOff": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "CrashLoopBackOff",
					DataUpdateIndex: "Unknown",
				},
				3: {
					Replica:         "10.10.10.12",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       4,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "0",
				TotalReadTime:        "0",
				TotalWriteTime:       "0",
				TotalWriteBlockCount: "0",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"StatsStd": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "4",
				TotalReadTime:        "12",
				TotalWriteTime:       "16",
				TotalWriteBlockCount: "15",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"ReadIOPSIsNotZero": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "10",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "4",
				TotalReadTime:        "12",
				TotalWriteTime:       "16",
				TotalWriteBlockCount: "15",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "20",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
		"WriteIOPSIsZero": {
			cmdOptions: &CmdVolumeOptions{
				json:    "",
				volName: "vol1",
			},
			replicaStats: map[int]*ReplicaStats{
				0: {
					Replica:         "10.10.10.10",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				1: {
					Replica:         "10.10.10.11",
					Status:          "Online",
					DataUpdateIndex: "1",
				},
				2: {
					Replica:         "nil",
					Status:          "Offline",
					DataUpdateIndex: "Unknown",
				},
			},
			initialStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "0",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "3",
				TotalReadTime:        "10",
				TotalWriteTime:       "15",
				TotalWriteBlockCount: "10",
				UpTime:               13162.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			finalStats: v1.VolumeMetrics{
				Name:                 "vol1",
				ReadIOPS:             "10",
				ReplicaCounter:       6,
				RevisionCounter:      100,
				SectorSize:           "4096",
				Size:                 "1073741824",
				TotalReadBlockCount:  "4",
				TotalReadTime:        "12",
				TotalWriteTime:       "16",
				TotalWriteBlockCount: "15",
				UpTime:               13170.971420756,
				UsedBlocks:           "1048576",
				UsedLogicalBlocks:    "1048576",
				WriteIOPS:            "15",
			},
			volume: VolumeInfo{
				Volume: v1alpha1.CASVolume{
					ObjectMeta: metav1.ObjectMeta{
						Annotations: map[string]string{
							"vsm.openebs.io/controller-ips":    "10.48.1.17",
							"vsm.openebs.io/iqn":               "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/cluster-ips":           "10.51.242.184",
							"openebs.io/iqn":                   "iqn.2016-09.com.openebs.jiva:default-testclaimjiva",
							"openebs.io/replica-status":        "running, running, running",
							"vsm.openebs.io/cluster-ips":       "10.51.242.184",
							"vsm.openebs.io/replica-status":    "running, running, running",
							"vsm.openebs.io/volume-size":       "5G",
							"openebs.io/controller-ips":        "10.48.1.17",
							"openebs.io/volume-size":           "5G",
							"vsm.openebs.io/replica-count":     "3",
							"vsm.openebs.io/replica-ips":       "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/controller-status":     "running,running",
							"openebs.io/replica-count":         "3",
							"vsm.openebs.io/controller-status": "running,running",
							"openebs.io/replica-ips":           "10.48.0.7, 10.48.1.18, 10.48.2.7",
							"openebs.io/targetportals":         "10.51.242.184:3260",
							"vsm.openebs.io/targetportals":     "10.51.242.184:3260",
						},
					},
					Spec: v1alpha1.CASVolumeSpec{
						CapacitySpec: v1alpha1.CapacitySpec{"5G"},
						ISCSISpec: v1alpha1.ISCSISpec{
							IQNSpec:          v1alpha1.IQNSpec{"iqn.2016-09.com.openebs.jiva:<no value>"},
							TargetIPSpec:     v1alpha1.TargetIPSpec{"<no value>"},
							TargetPortSpec:   v1alpha1.TargetPortSpec{"3260"},
							TargetPortalSpec: v1alpha1.TargetPortalSpec{"<no value>:3260"},
						},
						CasType:  "jiva",
						Replicas: "1",
					},
				},
			},
			output: nil,
		},
	}
	for name, tt := range validStats {
		t.Run(name, func(t *testing.T) {
			if got := displayStats(&tt.volume, tt.cmdOptions, tt.replicaStats, tt.initialStats, tt.finalStats); got != tt.output {
				t.Fatalf("displayStats(%v,%v, %v, %v, %v) => %v, want %v", &tt.volume, tt.cmdOptions, tt.replicaStats, tt.initialStats, tt.finalStats, got, tt.output)
			}
		})
	}

}
