# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Timeout allowed while waiting for the machine to boot.
  # The unit of measurements is in Seconds.
  config.vm.boot_timeout = 500


  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  # Enable provisioning with Shell provisioner. Additional provisioners such
  # as Shell, Puppet, Chef, Ansible, Salt, and Docker are also available. Please
  # see the documentation for more information about their specific syntax and 
  # use.
  
  # The script mentioned here will be uploaded & executed.
  config.vm.provision "shell",
    path: "setup-docker.sh"
  
  # Note - This is not inline script execution. 
  # Inline refers to the script that is already available in the guest.
  # Note - This script will be copied to each VM.
  # Operator need to ssh to each VM & run this script manually.
  config.vm.provision "file", 
    source: "./create-etcdcluster.sh", 
    destination: "create-etcdcluster.sh"
  
  # Define 3 VMs required to set up an etcd cluster.
  # Each of these VMs are set with private network space.
  config.vm.define "etcd0" do |etcd0|
    etcd0.vm.network "private_network", ip: "192.168.60.10"
  end
  
  config.vm.define "etcd1" do |etcd1|
    etcd1.vm.network "private_network", ip: "192.168.60.11"
  end

  config.vm.define "etcd2" do |etcd2|
    etcd2.vm.network "private_network", ip: "192.168.60.12"
  end
  
end
