/*
Copyright 2017 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/openebs/maya/pkg/apis/openebs.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VolumePolicyLister helps list VolumePolicies.
type VolumePolicyLister interface {
	// List lists all VolumePolicies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.VolumePolicy, err error)
	// Get retrieves the VolumePolicy from the index for a given name.
	Get(name string) (*v1alpha1.VolumePolicy, error)
	VolumePolicyListerExpansion
}

// volumePolicyLister implements the VolumePolicyLister interface.
type volumePolicyLister struct {
	indexer cache.Indexer
}

// NewVolumePolicyLister returns a new VolumePolicyLister.
func NewVolumePolicyLister(indexer cache.Indexer) VolumePolicyLister {
	return &volumePolicyLister{indexer: indexer}
}

// List lists all VolumePolicies in the indexer.
func (s *volumePolicyLister) List(selector labels.Selector) (ret []*v1alpha1.VolumePolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VolumePolicy))
	})
	return ret, err
}

// Get retrieves the VolumePolicy from the index for a given name.
func (s *volumePolicyLister) Get(name string) (*v1alpha1.VolumePolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("volumepolicy"), name)
	}
	return obj.(*v1alpha1.VolumePolicy), nil
}
