// +build !ignore_autogenerated

/*
Copyright 2019 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CStorPool) DeepCopyInto(out *CStorPool) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(ResourceFlags)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CStorPool.
func (in *CStorPool) DeepCopy() *CStorPool {
	if in == nil {
		return nil
	}
	out := new(CStorPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CStorVolume) DeepCopyInto(out *CStorVolume) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(ResourceFlags)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CStorVolume.
func (in *CStorVolume) DeepCopy() *CStorVolume {
	if in == nil {
		return nil
	}
	out := new(CStorVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flags) DeepCopyInto(out *Flags) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flags.
func (in *Flags) DeepCopy() *Flags {
	if in == nil {
		return nil
	}
	out := new(Flags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JivaVolume) DeepCopyInto(out *JivaVolume) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(ResourceFlags)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JivaVolume.
func (in *JivaVolume) DeepCopy() *JivaVolume {
	if in == nil {
		return nil
	}
	out := new(JivaVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFlags) DeepCopyInto(out *ResourceFlags) {
	*out = *in
	if in.IgnoreStepsOnError != nil {
		in, out := &in.IgnoreStepsOnError, &out.IgnoreStepsOnError
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFlags.
func (in *ResourceFlags) DeepCopy() *ResourceFlags {
	if in == nil {
		return nil
	}
	out := new(ResourceFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	if in.JivaVolume != nil {
		in, out := &in.JivaVolume, &out.JivaVolume
		*out = new(JivaVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.CStorVolume != nil {
		in, out := &in.CStorVolume, &out.CStorVolume
		*out = new(CStorVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.CStorPool != nil {
		in, out := &in.CStorPool, &out.CStorPool
		*out = new(CStorPool)
		(*in).DeepCopyInto(*out)
	}
	if in.StoragePoolClaim != nil {
		in, out := &in.StoragePoolClaim, &out.StoragePoolClaim
		*out = new(StoragePoolClaim)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolClaim) DeepCopyInto(out *StoragePoolClaim) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(ResourceFlags)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolClaim.
func (in *StoragePoolClaim) DeepCopy() *StoragePoolClaim {
	if in == nil {
		return nil
	}
	out := new(StoragePoolClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeDetailedStatuses) DeepCopyInto(out *UpgradeDetailedStatuses) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastUpdatedTime.DeepCopyInto(&out.LastUpdatedTime)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeDetailedStatuses.
func (in *UpgradeDetailedStatuses) DeepCopy() *UpgradeDetailedStatuses {
	if in == nil {
		return nil
	}
	out := new(UpgradeDetailedStatuses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeTask) DeepCopyInto(out *UpgradeTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeTask.
func (in *UpgradeTask) DeepCopy() *UpgradeTask {
	if in == nil {
		return nil
	}
	out := new(UpgradeTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeTaskList) DeepCopyInto(out *UpgradeTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeTaskList.
func (in *UpgradeTaskList) DeepCopy() *UpgradeTaskList {
	if in == nil {
		return nil
	}
	out := new(UpgradeTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeTaskSpec) DeepCopyInto(out *UpgradeTaskSpec) {
	*out = *in
	out.Flags = in.Flags
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeTaskSpec.
func (in *UpgradeTaskSpec) DeepCopy() *UpgradeTaskSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeTaskStatus) DeepCopyInto(out *UpgradeTaskStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletedTime.DeepCopyInto(&out.CompletedTime)
	if in.UpgradeDetailedStatuses != nil {
		in, out := &in.UpgradeDetailedStatuses, &out.UpgradeDetailedStatuses
		*out = make([]UpgradeDetailedStatuses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeTaskStatus.
func (in *UpgradeTaskStatus) DeepCopy() *UpgradeTaskStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeTaskStatus)
	in.DeepCopyInto(out)
	return out
}
