/*
Copyright 2019 The OpenEBS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package pstatus

import (
	"fmt"
	"os/exec"
	"reflect"
	"runtime"
	"strings"

	"github.com/openebs/maya/pkg/zfs/cmd/v1alpha1/bin"
	"github.com/pkg/errors"
)

const (
	// Operation defines type of zfs operation
	Operation = "status"
)

//PoolStatus defines structure for pool 'Status' operation
type PoolStatus struct {
	//pool name
	Pool string

	// command string
	Command string

	// checks is list of predicate function used for validating object
	checks []PredicateFunc

	// error
	err error
}

// NewPoolStatus returns new instance of object PoolStatus
func NewPoolStatus() *PoolStatus {
	return &PoolStatus{}
}

// WithCheck add given check to checks list
func (p *PoolStatus) WithCheck(check ...PredicateFunc) *PoolStatus {
	p.checks = append(p.checks, check...)
	return p
}

// WithPool method fills the Pool field of PoolStatus object.
func (p *PoolStatus) WithPool(Pool string) *PoolStatus {
	p.Pool = Pool
	return p
}

// WithCommand method fills the Command field of PoolStatus object.
func (p *PoolStatus) WithCommand(Command string) *PoolStatus {
	p.Command = Command
	return p
}

// Validate is to validate generated PoolStatus object by builder
func (p *PoolStatus) Validate() *PoolStatus {
	for _, check := range p.checks {
		if !check(p) {
			p.err = errors.Wrapf(p.err, "validation failed {%v}", runtime.FuncForPC(reflect.ValueOf(check).Pointer()).Name())
		}
	}
	return p
}

// Execute is to execute generated PoolStatus object
func (p *PoolStatus) Execute() ([]byte, error) {
	p, err := p.Build()
	if err != nil {
		return nil, err
	}
	// execute command here
	return exec.Command(bin.ZPOOL, p.Command).CombinedOutput()
}

// Build returns the PoolStatus object generated by builder
func (p *PoolStatus) Build() (*PoolStatus, error) {
	var c strings.Builder
	p = p.Validate()
	p.appendCommand(c, fmt.Sprintf(" %s ", Operation))

	p.appendCommand(c, p.Pool)

	p.Command = c.String()
	return p, p.err
}

// appendCommand append string to given string builder
func (p *PoolStatus) appendCommand(c strings.Builder, cmd string) {
	_, err := c.WriteString(cmd)
	if err != nil {
		p.err = errors.Wrapf(p.err, "Failed to append cmd{%s} : %s", cmd, err.Error())
	}
}
