/*
Copyright 2019 The OpenEBS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package vsnapshotsend

import (
	"fmt"
	"os/exec"
	"reflect"
	"runtime"
	"strings"

	"github.com/openebs/maya/pkg/zfs/cmd/v1alpha1/bin"
	"github.com/pkg/errors"
)

const (
	// Operation defines type of zfs operation
	Operation = "send"
)

//VolumeSnapshotSend defines structure for volume 'Snapshot' operation
type VolumeSnapshotSend struct {
	//name of snapshot
	Snapshot string

	//name of dataset on which snapshot should be taken
	Dataset string

	//remote destination for snapshot send/recv using nc
	Target string

	// to send incremental snapshot
	LastSnapshot string

	// Generate a deduplicated stream
	Dedup bool

	// dry-run
	DryRun bool

	// use compression for zfs send
	EnableCompression bool

	// command string
	Command string

	// checks is list of predicate function used for validating object
	checks []PredicateFunc

	// error
	err error
}

// NewVolumeSnapshotSend returns new instance of object VolumeSnapshotSend
func NewVolumeSnapshotSend() *VolumeSnapshotSend {
	return &VolumeSnapshotSend{}
}

// WithCheck add given check to checks list
func (v *VolumeSnapshotSend) WithCheck(check ...PredicateFunc) *VolumeSnapshotSend {
	v.checks = append(v.checks, check...)
	return v
}

// WithSnapshot method fills the Snapshot field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithSnapshot(Snapshot string) *VolumeSnapshotSend {
	v.Snapshot = Snapshot
	return v
}

// WithDataset method fills the Dataset field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithDataset(Dataset string) *VolumeSnapshotSend {
	v.Dataset = Dataset
	return v
}

// WithTarget method fills the Target field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithTarget(Target string) *VolumeSnapshotSend {
	v.Target = Target
	return v
}

// WithDedup method fills the Dedup field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithDedup(Dedup bool) *VolumeSnapshotSend {
	v.Dedup = Dedup
	return v
}

// WithLastSnapshot method fills the LastSnapshot field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithLastSnapshot(LastSnapshot string) *VolumeSnapshotSend {
	v.LastSnapshot = LastSnapshot
	return v
}

// WithDryRun method fills the DryRun field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithDryRun(DryRun bool) *VolumeSnapshotSend {
	v.DryRun = DryRun
	return v
}

// WithEnableCompression method fills the EnableCompression field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithEnableCompression(EnableCompression bool) *VolumeSnapshotSend {
	v.EnableCompression = EnableCompression
	return v
}

// WithCommand method fills the Command field of VolumeSnapshotSend object.
func (v *VolumeSnapshotSend) WithCommand(Command string) *VolumeSnapshotSend {
	v.Command = Command
	return v
}

// Validate is to validate generated VolumeSnapshotSend object by builder
func (v *VolumeSnapshotSend) Validate() *VolumeSnapshotSend {
	for _, check := range v.checks {
		if !check(v) {
			v.err = errors.Wrapf(v.err, "validation failed {%v}", runtime.FuncForPC(reflect.ValueOf(check).Pointer()).Name())
		}
	}
	return v
}

// Execute is to execute generated VolumeSnapshotSend object
func (v *VolumeSnapshotSend) Execute() ([]byte, error) {
	v, err := v.Build()
	if err != nil {
		return nil, err
	}
	// execute command here
	return exec.Command(bin.ZFS, v.Command).CombinedOutput()
}

// Build returns the VolumeSnapshotSend object generated by builder
func (v *VolumeSnapshotSend) Build() (*VolumeSnapshotSend, error) {
	var c strings.Builder
	v = v.Validate()

	v.appendCommand(c, fmt.Sprintf(" %s ", Operation))
	if IsDedupSet()(v) {
		v.appendCommand(c, fmt.Sprintf(" -D "))
	}

	if IsLastSnapshotSet()(v) {
		v.appendCommand(c, fmt.Sprintf(" -i @%s ", v.LastSnapshot))
	}

	v.appendCommand(c, fmt.Sprintf(" %s@%s ", v.Dataset, v.Snapshot))
	v.appendCommand(c, fmt.Sprintf(" | nc %s", v.Target))

	v.Command = c.String()
	return v, v.err
}

// appendCommand append string to given string builder
func (v *VolumeSnapshotSend) appendCommand(c strings.Builder, cmd string) {
	_, err := c.WriteString(cmd)
	if err != nil {
		v.err = errors.Wrapf(v.err, "Failed to append cmd{%s} : %s", cmd, err.Error())
	}
}
