kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-testvolume-pvc
  namespace: openebs
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2G"
