apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-standard
  annotations:
    cas.openebs.io/create-volume-template: cast-standard-cstor-create-0.7.0
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "gkepooldemo"
provisioner: openebs.io/provisioner-iscsi
---
