#!/bin/bash
set -e

IMAGEID=$( sudo docker images -q openebs/m-apiserver:${IMAGE_TAG} )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  sudo docker login -u "${DNAME}" -p "${DPASS}";
  # Push image to docker hub
  sudo docker push openebs/m-apiserver:${IMAGE_TAG} ;
  if [ ! -z "${TRAVIS_TAG}" ] ; 
  then
    # Push with different tags if tagged as a release
    # When github is tagged with a release, then Travis will 
    # set the release tag in env TRAVIS_TAG
    sudo docker tag ${IMAGEID} openebs/m-apiserver:${TRAVIS_TAG}
    sudo docker push openebs/m-apiserver:${TRAVIS_TAG}; 
    sudo docker tag ${IMAGEID} openebs/m-apiserver:latest
    sudo docker push openebs/m-apiserver:latest; 
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/m-apiserver:${IMAGE_TAG} to docker hub"; 
fi;

# Push ci image to quay.io for security scanning
if [ ! -z "${QNAME}" ] && [ ! -z "${QPASS}" ]; 
then 
  sudo docker login -u "${QNAME}" -p "${QPASS}" quay.io;
  sudo docker tag ${IMAGEID} quay.io/openebs/m-apiserver:${IMAGE_TAG};
else
  echo "Missing quay.io credentials. Skip uploading openebs/m-apiserver:${IMAGE_TAG} to quay.io"; 
fi;
